### ISSUE TITLE
Cannot build on Ubuntu 18.04

### ISSUE THREAD

**Issue by flockster** [climech/grit#2]
Hi,
I'm having problems building the binary on my pc. 
I extracted the release to my scripts folder on /home/USERNAME/scripts/grit-0.2.0
After running `make && sudo make install` I get the following error message.

`can't load package: package /home/USERNAME/go/grit-0.2.0/cmd/grit: import "/home/USERNAME/go/grit-0.2.0/cmd/grit": cannot import absolute path`
`Makefile:15: recipe for target 'grit' failed`
`make: *** [grit] Error 1`

The System is Ubuntu 18.04.5 LTS.
gcc is 7.5.0
go is 1.10.4 linux/amd64

Thank you very much

**Comment by climech** [comment]
Grit requires at least go 1.14 to build properly (go modules were only added in v1.11-12). Updating go should solve the problem. 

I'll add a note about this to build instructions.

**Comment by flockster** [comment]
Perfect, that fixed it. 

I installed the go version from the official apt repo, unaware that it was that old. 
With go 1.16.3 it worked flawlessly.
