### ISSUE TITLE
Error building in osx 10.15.7

### ISSUE THREAD

**Issue by sahand12** [climech/grit#3]
- go version: 

go version go1.15.5 darwin/amd64

- gcc --version: 

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- Install output: 
make && sudo make install
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/jawher/mow.cli v1.2.0
go: downloading github.com/kirsle/configdir v0.0.0-20170128060238-e45d2f54772f
go: downloading github.com/climech/naturalsort v0.1.0
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
github.com/jawher/mow.cli/internal/flow
golang.org/x/sys/unix
github.com/kirsle/configdir
github.com/climech/naturalsort
github.com/jawher/mow.cli/internal/lexer
github.com/jawher/mow.cli/internal/container
github.com/jawher/mow.cli/internal/values
github.com/jawher/mow.cli/internal/matcher
github.com/jawher/mow.cli/internal/fsm
github.com/jawher/mow.cli/internal/parser
github.com/jawher/mow.cli
github.com/mattn/go-isatty
github.com/mattn/go-sqlite3
github.com/mattn/go-colorable
github.com/fatih/color
github.com/climech/grit/multitree
github.com/climech/grit/db
github.com/climech/grit/app
github.com/climech/grit/cmd/grit
Password:
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64

**Comment by climech** [comment]
Looks like the `-D` flag is a GNU thing, I removed it.

Please create a new issue if there's another problem with building, unfortunately I don't have a mac to test things on.

**Comment by sahand12** [comment]
thanks for the immediate response, but the issue continued this time with ''-- t "  illegal option

- make && sudo make install:
Password:
install: illegal option -- t
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64

**Comment by climech** [comment]
Turns out neither of the flags were actually needed :smile:
Let me know if it installs now.

**Comment by ron-wolf** [comment]
For future reference, the man page for `install` on macOS can be found [on the Unix forums](https://www.unix.com/man-page/osx/1/install/). The compatible flags are `-BbCcdfgMmopSsv`.

**Comment by ron-wolf** [comment]
Works now for the most part. Only problem is that it tries to install into `/usr/bin`, when user programs are best placed into `/usr/local/bin` on macOS. The latter is writeable without using `sudo`. Up to you though.
